spring.config.import=optional:file:.env[.properties]
spring.application.name=Library
spring.datasource.url=jdbc:postgresql://${PGHOST}:5432/${PGDATABASE}?sslmode=${PGSSLMODE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

server.tomcat.relaxed-query-chars=\u00E0,\u00E2,\u00E4,\u00E6,\u00E7,\u00E8,\u00E9,\u00EA,\u00EB,\u00EE,\u00EF,\u00F4,\u0153,\u00F9,\u00FB,\u00FC,y