INSERT INTO author (id, first_name, last_name)
VALUES (gen_random_uuid(), 'Antoine', 'de Saint-Exupéry'),
       (gen_random_uuid(), 'Victor', 'Hugo'),
       (gen_random_uuid(), 'Albert', 'Camus'),
       (gen_random_uuid(), 'Marcel', 'Proust'),
       (gen_random_uuid(), 'Gustave', 'Flaubert'),
       (gen_random_uuid(), 'Émile', 'Zola'),
       (gen_random_uuid(), 'Honoré', 'de Balzac'),
       (gen_random_uuid(), 'Françoise', 'Sagan'),
       (gen_random_uuid(), 'Marguerite', 'Yourcenar'),
       (gen_random_uuid(), 'Jean-Paul', 'Sartre'),
       (gen_random_uuid(), 'Simone', 'de Beauvoir'),
       (gen_random_uuid(), 'Alexandre', 'Dumas'),
       (gen_random_uuid(), 'Jules', 'Verne'),
       (gen_random_uuid(), 'George', 'Sand'),
       (gen_random_uuid(), 'Romain', 'Gary'),
       (gen_random_uuid(), 'Marie-Henri', 'Beyle'),
       (gen_random_uuid(), 'François-Marie', 'Arouet'),
       (gen_random_uuid(), 'Jean-Baptiste', 'Poquelin'),
       (gen_random_uuid(), 'Jean', 'Racine'),
       (gen_random_uuid(), 'Charles', 'Baudelaire'),
       (gen_random_uuid(), 'Blaise', 'Pascal'),
       (gen_random_uuid(), 'René', 'Descartes')
ON CONFLICT DO NOTHING;
